services:
  web:
    image: wugge/battery-price-monitor-frontend:latest
    networks:
      - internal
      - traefik
    restart: "unless-stopped"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.bpm-frontend.rule=Host(`bpm.wug.ge`)"
      - "traefik.http.services.bpm-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.bpm-frontend.tls=true"
      - "traefik.http.routers.bpm-frontend.entrypoints=websecure"
  api:
    image: wugge/battery-price-monitor-api:latest
    networks:
      - internal
      - traefik
    restart: "unless-stopped"
    expose:
      - 3001
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_PROD_URL: ${API_PROD_URL}
      EXPRESS_PORT: 3001
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.bpm-api.rule=Host(`bpm.wug.ge`) && PathPrefix(`/api`)"
      - "traefik.http.services.bpm-api.loadbalancer.server.port=3001"
      - "traefik.http.routers.bpm-api.middlewares=bpm-api"
      - "traefik.http.middlewares.bpm-api.replacepathregex.regex=^/api/(.*)"
      - "traefik.http.middlewares.bpm-api.replacepathregex.replacement=/$$1"
      - "traefik.http.routers.bpm-api.tls=true"
      - "traefik.http.routers.bpm-api.entrypoints=websecure"
  bpm-db:
    image: mariadb:latest
    ports:
      - ${PUBLIC_DB_PORT:-3886}:3306
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bpm_db_volume:/var/lib/mysql
  redis:
    image: redis:8
    networks:
      - internal


volumes:
  bpm_db_volume:

networks:
  internal: {}
  traefik:
    external: true
    name: traefik_default